num_classes: 365            # number of classes
img_size: 224               # input image size

dataset_dir: '../Datasets/places365standard_easyformat/places365_standard' # '../Datasets/places365standard_easyformat/places365_standard' | '../Datasets/CUB_200_2011'

pretrained_weights: '' # path to pretrained weights - (http://places2.csail.mit.edu/models_places365/resnet18_places365.pth.tar)
resume: ''                        # Checkpoint resuming | path to latest checkpoint - (NotUse: None)

use_freeze_backbone: False  # freeze backbone when transfer-learning
use_dataLoaderCache: True   # use cache for faster dataloading(but use more memory)
use_amp: False              # use automatic mixed precision

arch: 'resnet18'            # model architecture in torchvision.models(e.g. resnet18, vgg, etc)
epochs: 90                  # number of epochs to train

scheduler: 'cosine'         # (cosine, cosine_warmup, step, multistep, linear)
lr: 0.001                   # starting learning rate(finetune or transfer-learning needs small lr, e.g. 0.00001)
batch_size: 256               # batch size
workers: 8                  # number of data loading workers

optimizer: 'adamw'          # (adamw, sgd, fused_adam, fused_lamb)
momentum: 0.9               # momentum in Optimizer
weight_decay: 0.001         # weight decay in Optimizer
label_smoothing: 0.1        # label smoothing(default: 0.1)

evaluate: False             # evaluate model on validation set
